spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore
    username: bookstore
    password: bookstore
  jpa:
    show-sql: true
  elasticsearch:
    uris: http://localhost:9200
  data:
    redis:
      host: localhost
      port: 6379